/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import entity.entitas_soal;
import intface.intface_soal;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author radhial22
 */
public class form_soal extends javax.swing.JFrame {
private intface_soal inf;
List<entitas_soal>daftar = new ArrayList<entitas_soal>();
 int r; 
 
 
 /**
     * Creates new form form_soal
     */
    public form_soal(intface_soal inf) {
        
        this.inf=inf;
        initComponents();

        //selectby();
        take();
       // count();
        isi();

       jTable2.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
              r=jTable2.getSelectedRow();
              if(r!=-1){
                  tampil();
              }
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        kd_soal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        soal = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        a = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        b = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        c = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        d = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        e = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jba = new javax.swing.JRadioButton();
        jbb = new javax.swing.JRadioButton();
        jbc = new javax.swing.JRadioButton();
        jbd = new javax.swing.JRadioButton();
        jbe = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(jTable2);

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kd_soal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kd_soalKeyTyped(evt);
            }
        });

        jLabel1.setText("Kode Soal :");

        jLabel2.setText("Soal :");

        soal.setColumns(20);
        soal.setRows(5);
        soal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soalKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(soal);

        jLabel3.setText("Pilihan A :");

        a.setColumns(20);
        a.setRows(5);
        jScrollPane2.setViewportView(a);

        jLabel4.setText("Pilihan B :");

        b.setColumns(20);
        b.setRows(5);
        jScrollPane3.setViewportView(b);

        jLabel5.setText("Pilihan C :");

        c.setColumns(20);
        c.setRows(5);
        jScrollPane4.setViewportView(c);

        jLabel6.setText("Pilihan D :");

        d.setColumns(20);
        d.setRows(5);
        jScrollPane5.setViewportView(d);

        jLabel7.setText("Pilihan E :");

        e.setColumns(20);
        e.setRows(5);
        jScrollPane6.setViewportView(e);

        jLabel8.setText("Jawaban :");

        buttonGroup1.add(jba);
        jba.setText("A");
        jba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jbb);
        jbb.setText("B");

        buttonGroup1.add(jbc);
        jbc.setText("C");

        buttonGroup1.add(jbd);
        jbd.setText("D");

        buttonGroup1.add(jbe);
        jbe.setText("E");

        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Ubah");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Hapus");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Batal");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jTable1);

        jButton2.setText("next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2)
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel4)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel5)
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel6)
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(9, 9, 9)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jButton5)
                                .addGap(7, 7, 7)
                                .addComponent(jButton6))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(jbc))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jbb))
                                    .addComponent(jba))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbd)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jbe)))))))
                .addGap(66, 66, 66)
                .addComponent(jScrollPane7))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(kd_soal, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel7)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(264, 264, 264)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(kd_soal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jbc)
                            .addComponent(jbb)
                            .addComponent(jba)
                            .addComponent(jbd)
                            .addComponent(jbe)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jba.getAccessibleContext().setAccessibleParent(jLabel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void next(){
        int row = jTable2.getSelectedRow();
        int b =  jTable2.getRowCount();
        int c = jTable2.getRowCount();
        entitas_soal ent = new entitas_soal();
        
      
        b-=1;
        if(row==b){
            row=b;
        }else {
            row+=1;
        }
        jTable2.changeSelection(row, WIDTH, false, false);
         int i = jTable2.getSelectedRow();
        
        
        
    }
    
   void count(){
        try {
            entitas_soal ent = new entitas_soal();
            ent=inf.count();
            
        } catch (RemoteException ex) {
            Logger.getLogger(form_soal.class.getName()).log(Level.SEVERE, null, ex);
        }
                
   }
   
    String test(String source){
        
       String result = "";
    String[] splitString = source.split(" ");
    for(String target : splitString){
        result += Character.toUpperCase(target.charAt(0))
                + target.substring(1) + " ";
       
    }
    return result.trim();
    }
    
  void test1(String input){
      String out = input.substring(0,1).toUpperCase() + input.substring(0,1).toUpperCase();
     
  } 
    void isi(){
    Object dat [][]=new Object[daftar.size()][2];
    int i =0;
    for(entitas_soal ent:daftar){
        dat[i][0]=ent.getKd_soal();
        dat[i][1]=ent.getSoal();
        i++;
    }
    String nmf[]={"Kode Soal","Soal"};
    jTable2.setModel(new DefaultTableModel(dat, nmf));
    TableColumn kl1 = jTable2.getColumnModel().getColumn(0);
    TableColumn kl2 =jTable2.getColumnModel().getColumn(1);
    kl1.setPreferredWidth(50);
    kl2.setPreferredWidth(400);
    jScrollPane8.setViewportView(jTable2);
}

void take(){
        try {
            daftar=inf.getall();
        } catch (RemoteException ex) {
            Logger.getLogger(form_soal.class.getName()).log(Level.SEVERE, null, ex);
        }
}
void selectby(){
        try {
            entitas_soal ent = new entitas_soal();
                        ent=inf.selectby(kd_soal.getText());
                        soal.setText(ent.getSoal());
                        a.setText(ent.getPilihan1());
                        b.setText(ent.getPilihan2());
                        c.setText(ent.getPilihan3());
                        d.setText(ent.getPilihan4());
                        e.setText(ent.getPilihan5());
                        if(ent.getBenar().equalsIgnoreCase("A")){
                            jba.setSelected(true);
                        }else if(ent.getBenar().equalsIgnoreCase("B")){
                            jbb.setSelected(true);
                        }else if(ent.getBenar().equalsIgnoreCase("C")){
                            jbc.setSelected(true);
                        }else if(ent.getBenar().equalsIgnoreCase("D")){
                            jbd.setSelected(true);
                        }else if(ent.getBenar().equalsIgnoreCase("E")){
                            jbe.setSelected(true);
                        }
        } catch (RemoteException ex) {
            Logger.getLogger(form_soal.class.getName()).log(Level.SEVERE, null, ex);
        }
}
void tampil(){
    entitas_soal ent = daftar.get(r);
    kd_soal.setText(ent.getKd_soal());
    soal.setText(ent.getSoal());
    a.setText(ent.getPilihan1());
    b.setText(ent.getPilihan2());
    c.setText(ent.getPilihan3());
    d.setText(ent.getPilihan4());
    e.setText(ent.getPilihan5());
     if(ent.getBenar().equalsIgnoreCase("A")){
                    jba.setSelected(true);
                }else if(ent.getBenar().equalsIgnoreCase("B")){
                    jbb.setSelected(true);
                }else if(ent.getBenar().equalsIgnoreCase("C")){
                    jbc.setSelected(true);
                }else if(ent.getBenar().equalsIgnoreCase("D")){
                    jbd.setSelected(true);
                }else if(ent.getBenar().equalsIgnoreCase("E")){
                    jbe.setSelected(true);
    }
}
    private void jbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            entitas_soal ent = new entitas_soal();
            ent.setKd_soal(kd_soal.getText());
            ent.setSoal(soal.getText());
            ent.setPilihan1(a.getText());
            ent.setPilihan2(b.getText());
            ent.setPilihan3(c.getText());
            ent.setPilihan4(d.getText());
            ent.setPilihan5(e.getText());
            if(jba.isSelected()){
                ent.setBenar("A");
            }else if(jbb.isSelected()){
                ent.setBenar("B");
            }else if(jbc.isSelected()){
                ent.setBenar("C");
            }else if(jbd.isSelected()){
                ent.setBenar("D");
            }else if(jbe.isSelected()){
                ent.setBenar("E");
            }
            inf.insert(ent);
            take();
            isi();
        } catch (RemoteException ex) {
            Logger.getLogger(form_soal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Ada Masalah Dengan Koneksi Anda, Cek Koneksi Jaringan Anda dan Status Server");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // TODO add your handling code here:
            entitas_soal ent = new entitas_soal();
            ent.setKd_soal(kd_soal.getText());
                ent.setSoal(soal.getText());
                ent.setPilihan1(a.getText());
                ent.setPilihan2(b.getText());
                ent.setPilihan3(c.getText());
                ent.setPilihan4(d.getText());
                ent.setPilihan5(e.getText());
                if(jba.isSelected()){
                    ent.setBenar("A");
                }else if(jbb.isSelected()){
                    ent.setBenar("B");
                }else if(jbc.isSelected()){
                    ent.setBenar("C");
                }else if(jbd.isSelected()){
                    ent.setBenar("D");
                }else if(jbe.isSelected()){
                    ent.setBenar("E");
                }
                inf.update(ent);
                take();
                isi();
        } catch (RemoteException ex) {
            Logger.getLogger(form_soal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            // TODO add your handling code here:
            String kd = kd_soal.getText();
            inf.delete(kd);
            take();
            isi();
        } catch (RemoteException ex) {
            Logger.getLogger(form_soal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void kd_soalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kd_soalKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()==KeyEvent.VK_ENTER){
            try {
                entitas_soal ent = new entitas_soal();
                ent=inf.selectby(kd_soal.getText());
                soal.setText(ent.getSoal());
                a.setText(ent.getPilihan1());
                b.setText(ent.getPilihan2());
                c.setText(ent.getPilihan3());
                d.setText(ent.getPilihan4());
                e.setText(ent.getPilihan5());
                if(ent.getBenar().equalsIgnoreCase("A")){
                    jba.setSelected(true);
                }else if(ent.getBenar().equalsIgnoreCase("B")){
                    jbb.setSelected(true);
                }else if(ent.getBenar().equalsIgnoreCase("C")){
                    jbc.setSelected(true);
                }else if(ent.getBenar().equalsIgnoreCase("D")){
                    jbd.setSelected(true);
                }else if(ent.getBenar().equalsIgnoreCase("E")){
                    jbe.setSelected(true);
                }
                if(ent.getKd_soal().equals("01")){
                    jButton1.setVisible(false);
                }
            } catch (RemoteException ex) {
                Logger.getLogger(form_soal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_kd_soalKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        next();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void soalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soalKeyTyped
        // TODO add your handling code here:
//        if(evt.getKeyChar()==KeyEvent.VK_ENTER){
//            test1(soal.getText());
//        }
    }//GEN-LAST:event_soalKeyTyped

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i = jTable2.getSelectedRow();
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

   void back(){
       try{

        int processComplete; // to verify that either process completed or not

    Process runtimeProcess = Runtime.getRuntime().exec("C:\\xampp\\mysql\\bin\\mysqldump -u javauser -pjavauser -r D:/back.sql");


                }catch(Exception e){

                    JOptionPane.showMessageDialog(null,e);//exeception handling

                    }

   }
   void back2(){
        try {
            // TODO add your handling code here:
            int complete;
            Process runtProcess = Runtime.getRuntime().exec("C:\\xampp\\mysql\\bin\\mysqldump -u javauser -pjavauser -r D:/back.sql");
            
            complete = runtProcess.waitFor();
            if(complete==1){
                JOptionPane.showMessageDialog(this, "tidak berhasil");
            }else if(complete==0){
                JOptionPane.showMessageDialog(this, "berhasil");
            }
            
        } catch (InterruptedException ex) {
            Logger.getLogger(form_soal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(form_soal.class.getName()).log(Level.SEVERE, null, ex);
        }
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea a;
    private javax.swing.JTextArea b;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea c;
    private javax.swing.JTextArea d;
    private javax.swing.JTextArea e;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JRadioButton jba;
    private javax.swing.JRadioButton jbb;
    private javax.swing.JRadioButton jbc;
    private javax.swing.JRadioButton jbd;
    private javax.swing.JRadioButton jbe;
    private javax.swing.JTextField kd_soal;
    private javax.swing.JTextArea soal;
    // End of variables declaration//GEN-END:variables
}
