/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Indexpkg;

import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andri
 */
public class InputNilai extends javax.swing.JFrame {

    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    char type;
    int mtk = 0,ipa=0,bin=0,jlh=0,rata=0;
    
    
    public InputNilai() {
        initComponents();
        jm.setVisible(false);
        rt.setVisible(false);
    }
    public InputNilai(String a,String b) {
        initComponents();
        jnis.setText(a);
        jnama.setText(b);
        jm.setVisible(false);
        rt.setVisible(false);
    }
    
    
    
    public void kosong(){
        jmtk.setText(null);
        jipa.setText(null);
        jbin.setText(null);
    }
    public void hitung(){
        mtk = Integer.parseInt(jmtk.getText());
        ipa = Integer.parseInt(jipa.getText());
        bin = Integer.parseInt(jbin.getText());
        jlh = mtk+ipa+bin;
        jm.setText(String.valueOf(jlh));
        rata = jlh/3;
        rt.setText(String.valueOf(rata));
        
        System.out.println("jumlah = "+jlh);
        System.err.println("rata = "+rata);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jnis = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jnama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jmtk = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jipa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jbin = new javax.swing.JTextField();
        simpan = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        simpan1 = new javax.swing.JLabel();
        jm = new javax.swing.JLabel();
        rt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 115, 130));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INPUT NILAI");

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("NIS");

        jnis.setEditable(false);
        jnis.setBackground(new java.awt.Color(0, 115, 130));
        jnis.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jnis.setForeground(new java.awt.Color(0, 255, 255));
        jnis.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 255)));
        jnis.setFocusable(false);

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("Nama");

        jnama.setEditable(false);
        jnama.setBackground(new java.awt.Color(0, 115, 130));
        jnama.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jnama.setForeground(new java.awt.Color(0, 255, 255));
        jnama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 255)));
        jnama.setFocusable(false);

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setText("Matematika");

        jmtk.setBackground(new java.awt.Color(0, 115, 130));
        jmtk.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jmtk.setForeground(new java.awt.Color(0, 255, 255));
        jmtk.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 255)));
        jmtk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jmtkKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 255));
        jLabel5.setText("IPA");

        jipa.setBackground(new java.awt.Color(0, 115, 130));
        jipa.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jipa.setForeground(new java.awt.Color(0, 255, 255));
        jipa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 255)));
        jipa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jipaActionPerformed(evt);
            }
        });
        jipa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jipaKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setText("B. Indonesia");

        jbin.setBackground(new java.awt.Color(0, 115, 130));
        jbin.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 12)); // NOI18N
        jbin.setForeground(new java.awt.Color(0, 255, 255));
        jbin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 255, 255)));
        jbin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jbinKeyTyped(evt);
            }
        });

        simpan.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        simpan.setForeground(new java.awt.Color(64, 224, 208));
        simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Save_Archive_30px.png"))); // NOI18N
        simpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                simpanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                simpanMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(64, 224, 208));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/back.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });

        simpan1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 12)); // NOI18N
        simpan1.setForeground(new java.awt.Color(64, 224, 208));
        simpan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_Erase_30px.png"))); // NOI18N
        simpan1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpan1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                simpan1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                simpan1MouseExited(evt);
            }
        });

        jm.setText("jLabel7");

        rt.setText("jLabel8");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(71, 71, 71)
                .addComponent(jnis, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addGap(57, 57, 57)
                .addComponent(jnama, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(simpan)
                .addGap(75, 75, 75)
                .addComponent(simpan1)
                .addGap(105, 105, 105)
                .addComponent(jLabel9))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(24, 24, 24)
                        .addComponent(jbin))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(72, 72, 72)
                        .addComponent(jipa))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26)
                        .addComponent(jmtk, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jm)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2))
                    .addComponent(jnis, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3))
                    .addComponent(jnama, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addComponent(jmtk, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5))
                    .addComponent(jipa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6))
                    .addComponent(jbin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(simpan)
                    .addComponent(simpan1)
                    .addComponent(jLabel9))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jm)
                    .addComponent(rt))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jipaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jipaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jipaActionPerformed

    private void simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseClicked
        hitung();
        int id = 0;
        String sql = "INSERT INTO daftarnilai VALUES(?,?,?,?,?,?,?)";
        
        try {
            PreparedStatement stat = (PreparedStatement) conn.prepareStatement(sql);
            stat.setString(1, jnis.getText());
            stat.setString(2, jnama.getText());
            stat.setString(3, jmtk.getText());
            stat.setString(4, jipa.getText());
            stat.setString(5, jbin.getText());
            stat.setString(6, jm.getText());
            stat.setString(7, rt.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            this.dispose();
            new DaftarNilai().setVisible(true);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan "+e);
            jmtk.requestFocus();
        }
        
    }//GEN-LAST:event_simpanMouseClicked

    private void simpanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseEntered
        simpan.setText("SIMPAN");
    }//GEN-LAST:event_simpanMouseEntered

    private void simpanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseExited
        simpan.setText(null);
    }//GEN-LAST:event_simpanMouseExited

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        new DaftarNilai().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        jLabel9.setText("KEMBALI");
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        jLabel9.setText(null);
    }//GEN-LAST:event_jLabel9MouseExited

    private void simpan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpan1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_simpan1MouseClicked

    private void simpan1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpan1MouseEntered
        simpan1.setText("HAPUS");
    }//GEN-LAST:event_simpan1MouseEntered

    private void simpan1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpan1MouseExited
       simpan1.setText(null);
    }//GEN-LAST:event_simpan1MouseExited

    private void jmtkKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmtkKeyTyped
       
        type = evt.getKeyChar();
        if(Character.isAlphabetic(type)){
            evt.consume();
        }
    }//GEN-LAST:event_jmtkKeyTyped

    private void jipaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jipaKeyTyped
       type = evt.getKeyChar();
        if(Character.isAlphabetic(type)){
            evt.consume();
        }
    }//GEN-LAST:event_jipaKeyTyped

    private void jbinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbinKeyTyped
        type = evt.getKeyChar();
        if(Character.isAlphabetic(type)){
            evt.consume();
        }
    }//GEN-LAST:event_jbinKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputNilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jbin;
    private javax.swing.JTextField jipa;
    private javax.swing.JLabel jm;
    private javax.swing.JTextField jmtk;
    private javax.swing.JTextField jnama;
    private javax.swing.JTextField jnis;
    private javax.swing.JLabel rt;
    private javax.swing.JLabel simpan;
    private javax.swing.JLabel simpan1;
    // End of variables declaration//GEN-END:variables
}
