/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import ace.model_inSoal;
import entity.entitas_soal;
import intface.intface_soal;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.rmi.RemoteException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author radhial22
 */
public class form_soal extends javax.swing.JFrame {
private intface_soal inf;
List<entitas_soal>daftar = new ArrayList<entitas_soal>();
  model_inSoal model = new model_inSoal();
 int r; 
 boolean beda;
 
 /**
     * Creates new form form_soal
     */
    public form_soal(intface_soal inf) {
        
        this.inf=inf;
        initComponents();
enab(false);
        //selectby();
        take();
       // count();
        
        jTable1.setModel(model);
       jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
              r=jTable1.getSelectedRow();
              if(r!=-1){
                  entitas_soal ent = daftar.get(r);
    kd_soal.setText(ent.getKd_soal());
    soal.setText(ent.getSoal());
    txta.setText(ent.getPilihan1());
    b.setText(ent.getPilihan2());
    c.setText(ent.getPilihan3());
    d.setText(ent.getPilihan4());
   eeee.setText(ent.getPilihan5());
     if(ent.getBenar().equalsIgnoreCase("A")){
                    jba.setSelected(true);
                }else if(ent.getBenar().equalsIgnoreCase("B")){
                    jbb.setSelected(true);
                }else if(ent.getBenar().equalsIgnoreCase("C")){
                    jbc.setSelected(true);
                }else if(ent.getBenar().equalsIgnoreCase("D")){
                    jbd.setSelected(true);
                }else if(ent.getBenar().equalsIgnoreCase("E")){
                    jbe.setSelected(true);
    }
              }
            }
        });
        
    }
void text(){
    kd_soal.setText("");
    soal.setText("");
    txta.setText("");
    b.setText("");
    c.setText("");
    d.setText("");
    eeee.setText("");
}

void enab(boolean a){
    kd_soal.setEnabled(a);
    soal.setEnabled(a);
    txta.setEnabled(a);
    b.setEnabled(a);
    c.setEnabled(a);
    d.setEnabled(a);
    eeee.setEnabled(a);
    jba.setEnabled(a);
    jbb.setEnabled(a);
    jbc.setEnabled(a);
    jbd.setEnabled(a);
    jbe.setEnabled(a);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        panelMenu1 = new ace.panelMenu();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kd_soal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        soal = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txta = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        b = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        c = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        d = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        eeee = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jba = new javax.swing.JRadioButton();
        jbc = new javax.swing.JRadioButton();
        jbb = new javax.swing.JRadioButton();
        jbd = new javax.swing.JRadioButton();
        jbe = new javax.swing.JRadioButton();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(jTable2);

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 204));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/window_delete.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Form Soal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 51, 204)));
        jPanel1.setOpaque(false);

        jLabel1.setText("Kode Soal :");

        kd_soal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kd_soalKeyTyped(evt);
            }
        });

        jLabel2.setText("Soal :");

        soal.setColumns(20);
        soal.setRows(5);
        soal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                soalKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(soal);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jTable1);

        jLabel3.setText("Pilihan A :");

        txta.setColumns(20);
        txta.setRows(5);
        txta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtaKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txta);

        jLabel4.setText("Pilihan B :");

        b.setColumns(20);
        b.setRows(5);
        b.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(b);

        jLabel5.setText("Pilihan C :");

        c.setColumns(20);
        c.setRows(5);
        c.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(c);

        jLabel6.setText("Pilihan D :");

        d.setColumns(20);
        d.setRows(5);
        d.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dKeyTyped(evt);
            }
        });
        jScrollPane5.setViewportView(d);

        jLabel7.setText("Pilihan E :");

        eeee.setColumns(20);
        eeee.setRows(5);
        jScrollPane6.setViewportView(eeee);

        jLabel8.setText("Jawaban :");

        buttonGroup1.add(jba);
        jba.setText("A");
        jba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jbc);
        jbc.setText("C");

        buttonGroup1.add(jbb);
        jbb.setText("B");

        buttonGroup1.add(jbd);
        jbd.setText("D");

        buttonGroup1.add(jbe);
        jbe.setText("E");

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/delete.png"))); // NOI18N
        jButton7.setText("Hapus");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/arrow_right.png"))); // NOI18N
        jButton4.setText("Ubah");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/add.png"))); // NOI18N
        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/arrow_down.png"))); // NOI18N
        jButton5.setText("Simpan");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pict/replay.png"))); // NOI18N
        jButton6.setText("Batal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(6, 6, 6)
                            .addComponent(kd_soal, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addComponent(jLabel3)
                            .addGap(3, 3, 3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel2)
                            .addGap(13, 13, 13)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(66, 66, 66)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(60, 60, 60)
                                            .addComponent(jbc))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(30, 30, 30)
                                            .addComponent(jbb))
                                        .addComponent(jba))
                                    .addGap(7, 7, 7)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jbd)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(30, 30, 30)
                                            .addComponent(jbe))))
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(4, 4, 4)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(kd_soal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbc)
                    .addComponent(jbb)
                    .addComponent(jba)
                    .addComponent(jbd)
                    .addComponent(jbe)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jButton7))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton6)
                        .addComponent(jButton5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jba.getAccessibleContext().setAccessibleParent(jLabel1);

        javax.swing.GroupLayout panelMenu1Layout = new javax.swing.GroupLayout(panelMenu1);
        panelMenu1.setLayout(panelMenu1Layout);
        panelMenu1Layout.setHorizontalGroup(
            panelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenu1Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenu1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10)))
                .addContainerGap())
        );
        panelMenu1Layout.setVerticalGroup(
            panelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu1Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(panelMenu1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void next(){
        int row = jTable2.getSelectedRow();
        int b =  jTable2.getRowCount();
        int c = jTable2.getRowCount();
        entitas_soal ent = new entitas_soal();
        
  

        b-=1;
        if(row==b){
            row=b;
        }else {
            row+=1;
        }
        jTable2.changeSelection(row, WIDTH, false, false);
         int i = jTable2.getSelectedRow();
        
        
        
    }
    
   void count(){
        try {
            entitas_soal ent = new entitas_soal();
            ent=inf.count();
            jLabel10.setText(ent.getJumlah());
        } catch (RemoteException ex) {
            Logger.getLogger(form_soal.class.getName()).log(Level.SEVERE, null, ex);
        }
                
   }
   
    String test(String source){
        
       String result = "";
    String[] splitString = source.split(" ");
    for(String target : splitString){
        result += Character.toUpperCase(target.charAt(0))
                + target.substring(1) + " ";
        jLabel10.setText(target);
    }
    return result.trim();
    }
    
  void test1(String input){
      String out = input.substring(0,1).toUpperCase() + input.substring(0,1).toUpperCase();
      jLabel10.setText(out);
  } 
    void isi(){
    Object dat [][]=new Object[daftar.size()][2];
    int i =0;
    for(entitas_soal ent:daftar){
        dat[i][0]=ent.getKd_soal();
        dat[i][1]=ent.getSoal();
        i++;
    }
    String nmf[]={"Kode Soal","Soal"};
    jTable1.setModel(new DefaultTableModel(dat, nmf));
    TableColumn kl1 = jTable2.getColumnModel().getColumn(0);
    TableColumn kl2 =jTable2.getColumnModel().getColumn(1);
    kl1.setPreferredWidth(50);
    kl2.setPreferredWidth(400);
    jScrollPane8.setViewportView(jTable1);
}

void take(){
        try {
            daftar=inf.getall();
            model.setdata(daftar);
        } catch (RemoteException ex) {
            Logger.getLogger(form_soal.class.getName()).log(Level.SEVERE, null, ex);
        }
}
void selectby(){
        try {
            entitas_soal ent = new entitas_soal();
                        ent=inf.selectby(kd_soal.getText());
                        soal.setText(ent.getSoal());
                        txta.setText(ent.getPilihan1());
                        b.setText(ent.getPilihan2());
                        c.setText(ent.getPilihan3());
                        d.setText(ent.getPilihan4());
                        eeee.setText(ent.getPilihan5());
                        if(ent.getBenar().equalsIgnoreCase("A")){
                            jba.setSelected(true);
                        }else if(ent.getBenar().equalsIgnoreCase("B")){
                            jbb.setSelected(true);
                        }else if(ent.getBenar().equalsIgnoreCase("C")){
                            jbc.setSelected(true);
                        }else if(ent.getBenar().equalsIgnoreCase("D")){
                            jbd.setSelected(true);
                        }else if(ent.getBenar().equalsIgnoreCase("E")){
                            jbe.setSelected(true);
                        }
        } catch (RemoteException ex) {
            Logger.getLogger(form_soal.class.getName()).log(Level.SEVERE, null, ex);
        }
}
//void tampil(){
//    entitas_soal ent = daftar.get(r);
//    kd_soal.setText(ent.getKd_soal());
//    soal.setText(ent.getSoal());
//    a.setText(ent.getPilihan1());
//    b.setText(ent.getPilihan2());
//    c.setText(ent.getPilihan3());
//    d.setText(ent.getPilihan4());
//    e.setText(ent.getPilihan5());
//     if(ent.getBenar().equalsIgnoreCase("A")){
//                    jba.setSelected(true);
//                }else if(ent.getBenar().equalsIgnoreCase("B")){
//                    jbb.setSelected(true);
//                }else if(ent.getBenar().equalsIgnoreCase("C")){
//                    jbc.setSelected(true);
//                }else if(ent.getBenar().equalsIgnoreCase("D")){
//                    jbd.setSelected(true);
//                }else if(ent.getBenar().equalsIgnoreCase("E")){
//                    jbe.setSelected(true);
//    }
//}
    private void jbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        beda=true;
       enab(true);
       text();
       kd_soal.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          beda=false;
          enab(true);
           kd_soal.setEnabled(false);
           soal.requestFocus();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(beda==true){
            if(kd_soal.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Kode Soal Harap Diisi");
            kd_soal.requestFocus();
        }else
        try {
            // TODO add your handling code here:
            entitas_soal ent = new entitas_soal();
            ent.setKd_soal(kd_soal.getText());
            ent.setSoal(soal.getText());
            ent.setPilihan1(txta.getText());
            ent.setPilihan2(b.getText());
            ent.setPilihan3(c.getText());
            ent.setPilihan4(d.getText());
            ent.setPilihan5(eeee.getText());
            if(jba.isSelected()){
                ent.setBenar("A");
            }else if(jbb.isSelected()){
                ent.setBenar("B");
            }else if(jbc.isSelected()){
                ent.setBenar("C");
            }else if(jbd.isSelected()){
                ent.setBenar("D");
            }else if(jbe.isSelected()){
                ent.setBenar("E");
            }
            inf.insert(ent);
            take();
            text();
        } catch (RemoteException ex) {
            Logger.getLogger(form_soal.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex);
        }
        }else if(beda==false){
            if(kd_soal.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Pilih Soal Yang Akan di Ubah");
            }else{
                try {
                    entitas_soal ent = new entitas_soal();
              ent.setKd_soal(kd_soal.getText());
              ent.setSoal(soal.getText());
              ent.setPilihan1(txta.getText());
              ent.setPilihan2(b.getText());
              ent.setPilihan3(c.getText());
              ent.setPilihan4(d.getText());
              ent.setPilihan5(eeee.getText());
              if(jba.isSelected()){
                  ent.setBenar("A");
              }else if(jbb.isSelected()){
                  ent.setBenar("B");
              }else if(jbc.isSelected()){
                  ent.setBenar("C");
              }else if(jbd.isSelected()){
                  ent.setBenar("D");
              }else if(jbe.isSelected()){
                  ent.setBenar("E");
              }
              inf.update(ent);
              take();
            text();
                } catch (RemoteException ex) {
                    Logger.getLogger(form_soal.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, ex);
                }
            
            }
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void kd_soalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kd_soalKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()==KeyEvent.VK_TAB){
            soal.requestFocus();
        }
        
    }//GEN-LAST:event_kd_soalKeyTyped

    private void soalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soalKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()==KeyEvent.VK_TAB){
            txta.requestFocus();
        }
    }//GEN-LAST:event_soalKeyTyped

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i = jTable2.getSelectedRow();
        jLabel10.setText(String.valueOf(i));
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            String kd = kd_soal.getText();
            inf.delete(kd);
            take();
            
        } catch (RemoteException ex) {
            Logger.getLogger(form_soal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void txtaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()==KeyEvent.VK_TAB){
            b.requestFocus();
        }
    }//GEN-LAST:event_txtaKeyTyped

    private void bKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()==KeyEvent.VK_TAB){
            c.requestFocus();
        }
    }//GEN-LAST:event_bKeyTyped

    private void cKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()==KeyEvent.VK_TAB){
            d.requestFocus();
        }
    }//GEN-LAST:event_cKeyTyped

    private void dKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()==KeyEvent.VK_TAB){
            eeee.requestFocus();
        }
    }//GEN-LAST:event_dKeyTyped

   void back(){
       try{

        int processComplete; // to verify that either process completed or not

    Process runtimeProcess = Runtime.getRuntime().exec("C:\\xampp\\mysql\\bin\\mysqldump -u javauser -pjavauser -r D:/back.sql");


                }catch(Exception e){

                    JOptionPane.showMessageDialog(null,e);//exeception handling

                    }

   }
   void back2(){
        try {
            // TODO add your handling code here:
            int complete;
            Process runtProcess = Runtime.getRuntime().exec("C:\\xampp\\mysql\\bin\\mysqldump -u javauser -pjavauser -r D:/back.sql");
            
            complete = runtProcess.waitFor();
            if(complete==1){
                JOptionPane.showMessageDialog(this, "tidak berhasil");
            }else if(complete==0){
                JOptionPane.showMessageDialog(this, "berhasil");
            }
            
        } catch (InterruptedException ex) {
            Logger.getLogger(form_soal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(form_soal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
        
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea b;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea c;
    private javax.swing.JTextArea d;
    private javax.swing.JTextArea eeee;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JRadioButton jba;
    private javax.swing.JRadioButton jbb;
    private javax.swing.JRadioButton jbc;
    private javax.swing.JRadioButton jbd;
    private javax.swing.JRadioButton jbe;
    private javax.swing.JTextField kd_soal;
    private ace.panelMenu panelMenu1;
    private javax.swing.JTextArea soal;
    private javax.swing.JTextArea txta;
    // End of variables declaration//GEN-END:variables
}
